services:
  # Servicio para producción (main)
  web-prod:
    build: .
    container_name: web-prod
    ports:
      - "8080:80"
    restart: unless-stopped

  # Servicio para QA
  web-qa:
    build: .
    container_name: web-qa
    ports:
      - "8081:80"
    restart: unless-stopped

  # Servicio para desarrollo
  web-dev:
    build: .
    container_name: web-dev
    ports:
      - "8082:80"