version: '3.8'

services:
  web-main:
    build: .
    container_name: web-main
    ports:
      - "7300:80"
    restart: unless-stopped

  web-qa:
    build: .
    container_name: web-qa
    ports:
      - "7301:80"
    restart: unless-stopped

  web-dev:
    build: .
    container_name: web-dev
    ports:
      - "7302:80"
    restart: unless-stopped
